# Generated by Django 5.2.8 on 2025-11-18 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('knox', '0009_extend_authtoken_field'),
    ]

    operations = []
