# Generated by Django 5.1.7 on 2025-10-13 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('knox', '0009_extend_authtoken_field'),
    ]

    operations = []
