# Generated by Django 5.0.7 on 2024-07-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_dark_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme_color',
            field=models.CharField(
                choices=[
                    ('Green', 'Green'),
                    ('Blue', 'Blue'),
                    ('Gray', 'Gray'),
                    ('Red', 'Red'),
                    ('Pink', 'Pink'),
                    ('Orange', 'Orange'),
                ],
                default='Green',
                max_length=6,
            ),
        ),
    ]
