# Generated by Django 5.0.7 on 2024-08-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_theme_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pdfs_per_page',
            field=models.IntegerField(choices=[(5, '5'), (10, '10'), (25, '25'), (50, '50'), (100, '100')], default=25),
        ),
    ]
