# Generated by Django 5.1.1 on 2024-10-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_default_themes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='custom_theme_color',
            field=models.CharField(default='#ffa385', max_length=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='custom_theme_color_secondary',
            field=models.CharField(default='#cc826a', max_length=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='custom_theme_color_tertiary_1',
            field=models.CharField(default='#99614f', max_length=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='custom_theme_color_tertiary_2',
            field=models.CharField(default='#ffc7b5', max_length=7),
        ),
        migrations.AlterField(
            model_name='profile',
            name='theme_color',
            field=models.CharField(
                choices=[
                    ('Green', 'Green'),
                    ('Blue', 'Blue'),
                    ('Gray', 'Gray'),
                    ('Red', 'Red'),
                    ('Pink', 'Pink'),
                    ('Orange', 'Orange'),
                    ('Custom', 'Custom'),
                ],
                default='Red',
                max_length=6,
            ),
        ),
    ]
