# Generated by Django 5.1.3 on 2024-11-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_custom_theme_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pdf_inverted_mode',
            field=models.CharField(
                choices=[('Enabled', 'Enabled'), ('Disabled', 'Disabled')], default='Disabled', max_length=8
            ),
        ),
    ]
