# Generated by Django 5.1.4 on 2024-12-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_show_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tags_tree_mode',
            field=models.CharField(
                choices=[('Enabled', 'Enabled'), ('Disabled', 'Disabled')], default='Enabled', max_length=8
            ),
        ),
    ]
