# Generated by Django 5.1.4 on 2025-01-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_add_tags_tree_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_thumbnails',
            field=models.CharField(
                choices=[('Enabled', 'Enabled'), ('Disabled', 'Disabled')], default='Disabled', max_length=8
            ),
        ),
    ]
