# Generated by Django 5.1.5 on 2025-01-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_add_show_thumbnails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dark_mode',
            field=models.CharField(
                choices=[('Light', 'Light'), ('Dark', 'Dark'), ('Creme', 'Creme')], default='Dark', max_length=5
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='theme_color',
            field=models.CharField(
                choices=[
                    ('Green', 'Green'),
                    ('Blue', 'Blue'),
                    ('Gray', 'Gray'),
                    ('Red', 'Red'),
                    ('Pink', 'Pink'),
                    ('Orange', 'Orange'),
                    ('Brown', 'Brown'),
                    ('Custom', 'Custom'),
                ],
                default='Red',
                max_length=6,
            ),
        ),
    ]
