# Generated by Django 5.1.5 on 2025-02-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_add_creme_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pdf_sorting',
            field=models.CharField(
                choices=[
                    ('Newest', 'Newest'),
                    ('Oldest', 'Oldest'),
                    ('Name_asc', 'Name Asc'),
                    ('Name_desc', 'Name Desc'),
                    ('Most_viewed', 'Most Viewed'),
                    ('Least_viewed', 'Least Viewed'),
                    ('Recently_viewed', 'Recently Viewed'),
                ],
                default='Newest',
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name='profile',
            name='shared_pdf_sorting',
            field=models.CharField(
                choices=[
                    ('Newest', 'Newest'),
                    ('Oldest', 'Oldest'),
                    ('Name_asc', 'Name Asc'),
                    ('Name_desc', 'Name Desc'),
                ],
                default='Newest',
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_sorting',
            field=models.CharField(
                choices=[
                    ('Newest', 'Newest'),
                    ('Oldest', 'Oldest'),
                    ('Email_asc', 'Email Asc'),
                    ('Email_desc', 'Email Desc'),
                ],
                default='Newest',
                max_length=15,
            ),
        ),
    ]
