# Generated by Django 5.1.5 on 2025-02-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_persistant_sorting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tags_tree_mode',
        ),
        migrations.AddField(
            model_name='profile',
            name='tag_tree_mode',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tags_open',
            field=models.BooleanField(default=False),
        ),
    ]
