# Generated by Django 5.2.7 on 2025-10-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_tertiary_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pdf_keep_screen_awake',
            field=models.CharField(
                choices=[('Enabled', 'Enabled'), ('Disabled', 'Disabled')], default='Disabled', max_length=8
            ),
        ),
    ]
