# Generated by Django 5.2.7 on 2025-10-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_keep_screen_awake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dark_mode',
            field=models.CharField(
                choices=[('System', 'System'), ('Light', 'Light'), ('Dark', 'Dark'), ('Creme', 'Creme')],
                default='Dark',
                max_length=6,
            ),
        ),
    ]
