# Generated by Django 5.2.7 on 2025-11-06 17:50

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_add_dark_mode_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_time_nagged',
            field=models.DateTimeField(default=users.models.get_last_time_nagged_initial),
        ),
    ]
