# Generated by Django 5.2.7 on 2025-11-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_add_a_little_nagging'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='signatures',
            field=models.JSONField(default=dict),
        ),
    ]
