# Generated by Django 5.2.8 on 2025-11-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_add_pdf_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_collection_id',
            field=models.CharField(editable=False, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_workspace_id',
            field=models.CharField(editable=False, max_length=36, null=True),
        ),
    ]
