# Generated by Django 5.1 on 2024-10-02 21:55

import uuid

import django.db.models.deletion
import pdf.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_add_pdf_views'),
        ('users', '0005_add_pdfs_per_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedPdf',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('file', models.FileField(upload_to=pdf.models.get_qrcode_file_path)),
                ('description', models.TextField(blank=True, help_text='Optional', null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf.pdf')),
            ],
        ),
    ]
