# Generated by Django 5.1.1 on 2024-11-08 06:54

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0004_add_pdf_sharing_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='last_viewed_date',
            field=models.DateTimeField(
                default=datetime.datetime(2000, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), editable=False
            ),
        ),
    ]
