# Generated by Django 5.1.4 on 2024-12-11 07:28

# Remove the number_of_pages migration in order to not display a progress bar if the number of
# pages could not be extracted via pypdf. Some user have already migrated to the previous migration.
# Therefore, we delete the migration, so these users get the same behaviour.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0007_add_number_of_pdf_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='number_of_pages',
        ),
    ]
