# Generated by Django 5.1.4 on 2025-01-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0009_readd_number_of_pages_with_new_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional', null=True),
        ),
    ]
