# Generated by Django 5.1.4 on 2025-01-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0010_add_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pdf',
            name='starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional, supports Markdown', null=True),
        ),
    ]
