# Generated by Django 5.1.4 on 2025-01-12 21:03

from django.db import migrations, models
from pdf.models.pdf_models import get_thumbnail_path


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0011_add_starred_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='thumbnail',
            field=models.FileField(null=True, upload_to=get_thumbnail_path),
        ),
    ]
