# Generated by Django 5.1.4 on 2025-01-12 21:03

import pdf.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0011_add_starred_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='thumbnail',
            field=models.FileField(null=True, upload_to=pdf.models.get_thumbnail_path),
        ),
    ]
