# Generated by Django 5.1.5 on 2025-02-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0013_add_pdf_previews'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='revision',
            field=models.IntegerField(default=0),
        ),
    ]
