# Generated by Django 5.1.7 on 2025-03-24 16:51

from django.db import migrations, models
from pdf.service import PdfProcessingServices


def update_pdf_file_names(apps, schema_editor):
    """Rename pdfs, so that the file name is not a random ID but the pdf name."""

    pdf_model = apps.get_model("pdf", "Pdf")

    for pdf in pdf_model.objects.all():
        PdfProcessingServices.process_renaming_pdf(pdf)


def reverse_func(apps, schema_editor):  # pragma: no cover
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0015_add_comments_highlights'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='file_directory',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.RunPython(update_pdf_file_names, reverse_func),
    ]
