# Generated by Django 5.1.7 on 2025-04-04 10:41

import pdf.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0016_rename_pdfs_and_add_file_directory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='file',
            field=models.FileField(max_length=500, upload_to=pdf.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='file_directory',
            field=models.CharField(
                blank=True,
                help_text='Optional, save file in a sub directory of the pdf directory, e.g: important/pdfs',
                max_length=120,
                null=True,
            ),
        ),
    ]
