# Generated by Django 5.2.8 on 2025-11-16 13:54

import datetime

from django.db import migrations, models


def default_datetime():
    return datetime.datetime.now(tz=datetime.timezone.utc)


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0017_increase_pdf_file_field_max_lenght'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='name',
            field=models.CharField(default='pdf_name', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pdfcomment',
            name='creation_date',
            field=models.DateTimeField(default=default_datetime, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pdfcomment',
            name='page',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pdfcomment',
            name='text',
            field=models.TextField(default='dummy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pdfhighlight',
            name='creation_date',
            field=models.DateTimeField(default=default_datetime, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pdfhighlight',
            name='page',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pdfhighlight',
            name='text',
            field=models.TextField(default='dummy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sharedpdf',
            name='name',
            field=models.CharField(default='shared_pdf_name', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(default='date_name', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pdf',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Optional'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='file_directory',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Optional, save file in a sub directory of the pdf directory, e.g: important/pdfs',
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Optional, supports Markdown'),
        ),
        migrations.AlterField(
            model_name='sharedpdf',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Optional'),
        ),
    ]
