# Generated by Django 5.2.8 on 2025-11-20 17:40

import uuid

import django.db.models.deletion
import pdf.models.collection_models
import pdf.models.workspace_models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0018_remove_wrong_null_true'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                (
                    'id',
                    models.CharField(
                        default=pdf.models.collection_models.get_uuid4_str,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('name', models.CharField(max_length=50)),
                ('default_collection', models.BooleanField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                (
                    'id',
                    models.CharField(
                        default=pdf.models.workspace_models.get_uuid4_str,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('name', models.CharField(max_length=50)),
                ('personal_workspace', models.BooleanField(editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='pdf',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pdf.collection'),
        ),
        migrations.AddField(
            model_name='collection',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf.workspace'),
        ),
        migrations.AddField(
            model_name='tag',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pdf.workspace'),
        ),
        migrations.CreateModel(
            name='WorkspaceUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    'role',
                    models.CharField(
                        choices=[('Owner', 'Owner'), ('List', 'Admin'), ('Member', 'Member'), ('Guest', 'Guest')],
                        max_length=6,
                    ),
                ),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf.workspace')),
            ],
        ),
    ]
