# Generated by Django 5.2.8 on 2025-11-20 09:21

from django.db import migrations
from pdf.models.collection_models import Collection
from pdf.models.workspace_models import Workspace, WorkspaceRoles, WorkspaceUser


def fill_data(apps, schema_editor):
    """Fill the collection and workspace data for existing users"""

    profile_model = apps.get_model("users", "Profile")
    pdf_model = apps.get_model("pdf", "Pdf")
    tag_model = apps.get_model("pdf", "Tag")

    for profile_object in profile_model.objects.all():
        personal_workspace = Workspace.objects.create(
            id=profile_object.user.id, name='Personal', personal_workspace=True
        )
        default_collection = Collection.objects.create(
            id=profile_object.user.id, name='Default', default_collection=True, workspace=personal_workspace
        )
        WorkspaceUser.objects.create(
            workspace=personal_workspace, user_id=profile_object.user.id, role=WorkspaceRoles.OWNER
        )

        profile_object.current_workspace_id = personal_workspace.id
        profile_object.current_collection_id = default_collection.id
        profile_object.save()

        for pdf_object in pdf_model.objects.filter(owner__id=profile_object.id):
            pdf_object.collection_id = default_collection.id
            pdf_object.save()

        for tag_object in tag_model.objects.filter(owner__id=profile_object.id):
            tag_object.workspace_id = personal_workspace.id
            tag_object.save()


def reverse_func(apps, schema_editor):  # pragma: no cover
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0019_add_collections_workspaces'),
        ('users', '0024_add_current_collection_workspace'),
    ]

    operations = [
        migrations.RunPython(fill_data, reverse_func),
    ]
