# Generated by Django 5.2.8 on 2025-11-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0020_fill_collections_workspaces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaceuser',
            name='role',
            field=models.CharField(
                choices=[('Owner', 'Owner'), ('Admin', 'Admin'), ('Member', 'Member'), ('Guest', 'Guest')], max_length=6
            ),
        ),
    ]
