name: Release Charts

on:
  push:
    branches:
      - master
    paths:
      - helm-charts/pdfding/Chart.yaml

jobs:
  chart_release:
    name: Release Charts
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # chart releaser will not work without this param
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@cae68fefc6b5f367a0275617c9f83181ba54714f
        with:
          skip_existing: true
          mark_as_latest: false
          packages_with_index: true
          charts_dir: helm-charts
          pages_branch: gh-pages
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
